<?php include __DIR__. '/../header.html' ?>
	<div class="container">
		<div class="row">
			<h3>Listagem de categorias </h3>
			<table class="table">
				<thead>
				<tr>
					<th>ID</th>
					<th>Name</th>
				</tr>
				<tbody>
				<?php foreach ($categories as $category):?>
					<tr>
						<td><?php echo $category->getId(); ?></td>
						<td><?php echo $category->getName(); ?></td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
<?php include __DIR__. '/../footer.html' ?>